import os
import json
import time
import logging
from flask import Flask, request, jsonify
import yt_dlp

# إعداد السجلات
logging.basicConfig(level=logging.ERROR)
logger = logging.getLogger(__name__)

app = Flask(__name__)

# --- دالة مساعدة لتحويل ملف JSON إلى Netscape Cookies ---
def create_netscape_cookie_file(json_path, output_path):
    """
    تحويل ملف الكوكيز من صيغة JSON (المستخرج من الإضافات) 
    إلى صيغة Netscape التي تفهمها yt-dlp/wget
    """
    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            cookies = json.load(f)

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by application\n\n")

            for cookie in cookies:
                # التأكد من الحقول المطلوبة (قد تختلف الأسماء حسب الإضافة المستخدمة)
                domain = cookie.get('domain', '')
                # تحويل true/false إلى TRUE/FALSE
                flag_domain = 'TRUE' if domain.startswith('.') else 'FALSE'
                path = cookie.get('path', '/')
                secure = 'TRUE' if cookie.get('secure') else 'FALSE'
                
                # الحصول على وقت انتهاء الصلاحية
                # بعض الإضافات تسميه expirationDate وبعضها expiry
                expires = cookie.get('expirationDate', cookie.get('expiry', int(time.time()) + 31536000))
                expires = str(int(expires))
                
                name = cookie.get('name', '')
                value = cookie.get('value', '')

                # الكتابة بالترتيب القياسي لصيغة Netscape مفصولة بـ Tab
                f.write(f"{domain}\t{flag_domain}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")
        
        return True
    except Exception as e:
        logger.error(f"Error converting cookies: {e}")
        return False

@app.route('/api/download', methods=['GET', 'POST'])
def download_media():
    url = request.values.get('url')
    m_type = request.values.get('type', 'video')
    
    if not url:
        return jsonify({"status": "error", "message": "No URL provided"}), 400

    format_selector = 'bestaudio/best' if m_type == 'audio' else 'best' 

    ydl_opts = {
        'quiet': True,
        'no_warnings': True,
        'format': format_selector,
        'socket_timeout': 15, # زيادة طفيفة للمهلة
        'noplaylist': True,
        # 'forceurl': True, # يُفضل إزالته أحياناً للسماح باستخراج المعلومات كاملة أولاً
        'dump_single_json': True
    }

    # === التعامل مع ملف الكوكيز ===
    cookie_json_file = 'youtube.json'
    cookie_txt_file = 'cookies.txt'

    # إذا كان ملف json موجوداً، نقوم بتحويله واستخدامه
    if os.path.exists(cookie_json_file):
        if create_netscape_cookie_file(cookie_json_file, cookie_txt_file):
            ydl_opts['cookiefile'] = cookie_txt_file
            # عند استخدام الكوكيز، من الأفضل استخدام عميل Web لمحاكاة المتصفح بشكل صحيح
            ydl_opts['extractor_args'] = {
                'youtube': {
                    # نحاكي المتصفح لتقليل الشكوك، أو نحاكي الموبايل
                    # جرّب ['web'] لوحدها أولاً مع الكوكيز، إذا فشل جرب ['android']
                    'player_client': ['web'], 
                }
            }
        else:
             # إذا فشل التحويل نستخدم خيار الأندرويد كحل بديل بدون كوكيز
            ydl_opts['extractor_args'] = {'youtube': {'player_client': ['android']}}
    else:
        # لا يوجد ملف كوكيز، نستخدم عميل أندرويد لتجنب بعض مشاكل التوثيق
        ydl_opts['extractor_args'] = {'youtube': {'player_client': ['android']}}

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
            
            final_url = info.get('url')
            if not final_url:
                formats = info.get('formats', [])
                if formats:
                    final_url = formats[-1].get('url')
            
            protocol_type = "direct"
            if final_url and (".m3u8" in final_url or "manifest" in final_url):
                protocol_type = "stream_manifest"

            return jsonify({
                "status": "success",
                "title": info.get('title'),
                "url": final_url,
                "type": m_type,
                "protocol": protocol_type,
                "thumbnail": info.get('thumbnail'),
                "msg": "Data retrieved successfully"
            })

    except Exception as e:
        error_msg = str(e)
        # محاولة تنظيف الرسالة
        if "Sign in to confirm" in error_msg:
             # هذه الرسالة تعني أن الكوكيز غير صالحة أو الـ IP محظور تماماً
             clean_error = "YouTube blocking active. Try updating cookies."
        else:
             clean_error = error_msg.split(';')[0].replace('ERROR: ', '')

        logger.error(f"Failed: {error_msg}")
        return jsonify({
            "status": "error", 
            "message": clean_error,
            "tip": "Ensure 'youtube.json' is valid and contains active cookies from a logged-in browser."
        }), 400

@app.route('/')
def home():
    return "Service Running with Cookie Support"

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 10000))
    app.run(host='0.0.0.0', port=port)
