from flask import Flask, request, jsonify, Response, stream_with_context
import yt_dlp
import json
import os
import tempfile
import subprocess
import shutil

app = Flask(__name__)

FFMPEG_BIN = shutil.which("ffmpeg") or "ffmpeg"

def json_cookies_to_netscape(json_path):
    if not os.path.exists(json_path): return None
    try:
        with open(json_path, 'r', encoding='utf-8') as f: cookies = json.load(f)
        fd, temp_path = tempfile.mkstemp(suffix='.txt', text=True)
        with os.fdopen(fd, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n# Generated by Server\n\n")
            for c in cookies:
                domain, name, value = c.get('domain'), c.get('name'), c.get('value', '')
                if not domain or not name: continue
                flag = 'TRUE' if domain.startswith('.') else 'FALSE'
                path = c.get('path', '/')
                secure = 'TRUE' if c.get('secure') else 'FALSE'
                expiry = int(c.get('expirationDate', c.get('expiry', 0)) or 0)
                f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")
        return temp_path
    except Exception as e:
        print(f"Cookie Error: {e}"); return None

# ====================
# [API] البحث السريع
# ====================
@app.route('/api/search', methods=['GET'])
def search_youtube():
    query = request.args.get('q')
    limit = request.args.get('limit', '5')
    if not query: return jsonify({'error': 'Missing query'}), 400

    cookie_file = json_cookies_to_netscape('youtube.json')
    
    # تحسينات السرعة: تقليل البيانات المجلوبة
    ydl_opts = {
        'quiet': True, 'no_warnings': True, 'cookiefile': cookie_file,
        'extract_flat': True,  # ⚡ سرعة فائقة (لا يجلب روابط الفيديو الحقيقية الآن)
        'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/90.0.4430.212 Safari/537.36'}
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            res = ydl.extract_info(f"ytsearch{limit}:{query}", download=False)
            entries = res.get('entries', [])
            
            clean_results = []
            for item in entries:
                if not item: continue
                # تكوين الرابط يدوياً للسرعة بدل انتظار الفحص
                vid_url = item.get('url') if 'url' in item else f"https://www.youtube.com/watch?v={item['id']}"
                
                clean_results.append({
                    'title': item.get('title', 'Unknown'),
                    'url': vid_url,
                    'duration': item.get('duration', 0),
                    'uploader': item.get('uploader', 'Unknown')
                })
                
        if cookie_file and os.path.exists(cookie_file): os.unlink(cookie_file)
        return jsonify({'count': len(clean_results), 'results': clean_results})

    except Exception as e:
        if cookie_file and os.path.exists(cookie_file): os.unlink(cookie_file)
        return jsonify({'error': str(e)}), 500

# ==============================
# [API] التحميل السلس (Direct Pipe)
# ==============================
@app.route('/api/download', methods=['GET'])
def download_stream():
    url = request.args.get('url')
    m_type = request.args.get('type', 'video') # audio, video
    q_req = request.args.get('q', '720')
    out_fmt = request.args.get('fmt', 'mp4') # mp4, mp3
    
    if not url: return jsonify({'error': 'URL missing'}), 400
    
    cookie_file = json_cookies_to_netscape('youtube.json')

    # إعدادات متقدمة للحصول على رابط البث المباشر (Raw Stream URL)
    ydl_opts = {
        'quiet': True, 'no_warnings': True, 'cookiefile': cookie_file,
        'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/90.0.4430.212 Safari/537.36'}
    }
    
    # اختيار الجودة بدقة
    if m_type == 'audio':
        # نطلب أفضل صوت بصيغة m4a لسهولة التحويل
        ydl_opts['format'] = 'bestaudio[ext=m4a]/bestaudio'
    else:
        # للفيديو نطلب رابط واحد مدمج (لتجنب دمج الفيديو والصوت بالخادم)
        # هذا أسرع بكثير لأن yt-dlp لا يحتاج لاستخدام ffmpeg للدمج
        if q_req == 'best':
            ydl_opts['format'] = 'best'
        else:
            try: h = int(q_req)
            except: h = 720
            # نطلب فيديو بصيغة mp4 وجاهز (pre-merged) بارتفاع معين
            ydl_opts['format'] = f"best[ext=mp4][height<={h}]/best[ext=mp4]/best"

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
            stream_url = info.get('url') # رابط جوجل المباشر
            title = info.get('title', 'downloaded_file')
            
            # في بعض الحالات النادرة قد لا نحصل على رابط مباشر، نعيد المحاولة بصيغة عامة
            if not stream_url:
                stream_url = info['formats'][-1]['url']

    except Exception as e:
        if cookie_file: os.unlink(cookie_file)
        return jsonify({'error': f"Extractor Error: {str(e)}"}), 500

    if cookie_file: os.unlink(cookie_file)

    # 🚀 هنا التغيير الجوهري: Stream من المصدر لـ ffmpeg للمستخدم مباشرة
    # نستخدم pipe:1 للإجبار على الدفع الفوري
    ffmpeg_cmd = [
        FFMPEG_BIN, '-y',
        '-headers', 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/90.0.4430.212 Safari/537.36\r\n',
        '-i', stream_url, # الدخل هو الرابط المباشر
        '-c', 'copy',     # نسخ بدون إعادة ترميز (سرعة خارقة)
        '-f', 'mp4'       # الحاوية
    ]

    # ضبط المخرجات حسب النوع (بأسرع إعدادات ممكنة)
    final_filename = f"{title}.mp4"
    mime_type = "video/mp4"

    if m_type == 'audio':
        # للصوت: نحول بسرعة إلى mp3 باستخدام أقل إعدادات جودة مقبولة للسرعة
        # -q:a 4 تعني جودة متوسطة/عالية لكن سريعة
        ffmpeg_cmd = [
            FFMPEG_BIN, '-y',
            '-i', stream_url,
            '-vn', # حذف الفيديو
            '-acodec', 'libmp3lame', '-q:a', '4', 
            '-f', 'mp3'
        ]
        final_filename = f"{title}.mp3"
        mime_type = "audio/mpeg"
        out_fmt = "mp3"
    
    else:
        # للفيديو: يجب استخدام frag_keyframe للبث المباشر (Streaming) عبر HTTP
        # وإلا سينتظر ffmpeg حتى ينتهي الملف بالكامل ليكتب الـ header
        ffmpeg_cmd = [
            FFMPEG_BIN, '-y',
            '-i', stream_url,
            '-c', 'copy',
            '-movflags', 'frag_keyframe+empty_moov', # ⚡ السحر هنا (يبدأ التحميل فوراً)
            '-f', 'mp4'
        ]

    ffmpeg_cmd.append('-') # الإخراج للـ Stdout

    # تنظيف اسم الملف
    safe_name = "".join([c for c in final_filename if c.isalnum() or c in "._- "]).strip()
    if not safe_name: safe_name = f"download.{out_fmt}"

    # دالة المولد (Generator)
    def stream_ffmpeg():
        # bufsize=0 مهم جداً لعدم التخزين المؤقت
        process = subprocess.Popen(
            ffmpeg_cmd, 
            stdout=subprocess.PIPE, 
            stderr=subprocess.PIPE, 
            bufsize=0  
        )
        
        try:
            # قراءة قطع صغيرة (4KB) وإرسالها فوراً
            while True:
                chunk = process.stdout.read(4096)
                if not chunk: break
                yield chunk
        except GeneratorExit:
            process.kill()
        finally:
            if process.poll() is None: process.terminate()

    return Response(
        stream_with_context(stream_ffmpeg()),
        mimetype=mime_type,
        headers={
            "Content-Disposition": f'attachment; filename="{safe_name}"',
            # headers لمنع التخزين المؤقت في الطريق (Nginx/Proxy)
            "X-Accel-Buffering": "no",
            "Cache-Control": "no-cache"
        }
    )

if __name__ == '__main__':
    # Threaded=True مهم جداً للسماح بطلبات متزامنة
    app.run(host='0.0.0.0', port=5000, threaded=True)
